Repository jenkinsci/core-changelog-generator, pull requests merged in 2019-11, with the labels that each got.

#1 Require date in the changelog generator
  generate-jenkins-changelog.rb
Labels: bug

#2 Introduce a Dockerized version of the tool + Add support of generating YAML files as an output
  .dockerignore
  .gitignore
  Dockerfile
  README.md
  docker-runner.rb
  generate-jenkins-changelog.rb
  lts-backports-changelog.rb
Labels: enhancement

#4 Publish an official Docker image: jenkins/core-changelog-generator
  README.md
Labels: enhancement

#5 Make the weekly.yml link in lts-backports-changelog optional + Support HTTPS URLs as a source of weekly.yml in lts-backports-changelog+ Fix failures of lts-backports-changelog on platforms where bash is not a default shell
  Dockerfile
  README.md
  lts-backports-changelog.rb
Labels: bug, enhancement
